// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeoDxdMLCVZGfwbMiDK3yi7G0K0x3BvQc',
    appId: '1:857695741634:android:ce0760d589f1584b70bd5b',
    messagingSenderId: '857695741634',
    projectId: 'simple-task-app-788c5',
    storageBucket: 'simple-task-app-788c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs2s-UDT5muRqWsH2Y2zMYnVterPI-nNg',
    appId: '1:857695741634:ios:f8e554323e4a413470bd5b',
    messagingSenderId: '857695741634',
    projectId: 'simple-task-app-788c5',
    storageBucket: 'simple-task-app-788c5.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs2s-UDT5muRqWsH2Y2zMYnVterPI-nNg',
    appId: '1:857695741634:ios:f8e554323e4a413470bd5b',
    messagingSenderId: '857695741634',
    projectId: 'simple-task-app-788c5',
    storageBucket: 'simple-task-app-788c5.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKz7w900SPIAuQR-nyb7O4Hzw2XPJhFs4',
    appId: '1:857695741634:web:74e5c766dd9893bc70bd5b',
    messagingSenderId: '857695741634',
    projectId: 'simple-task-app-788c5',
    authDomain: 'simple-task-app-788c5.firebaseapp.com',
    storageBucket: 'simple-task-app-788c5.appspot.com',
    measurementId: 'G-43EG5Y8ZBE',
  );
}
